### ISSUE TITLE
Translated RU

### ISSUE THREAD

**Issue by BogdanMakarchuk** [Enes5519/EggWars#3]
I translated into Russian plugin, you do not need?

**Comment by Enes5519** [comment]
You turned you into the Russian language plugin?

**Comment by BogdanMakarchuk** [comment]
@Enes5519 Russian + English

**Comment by Enes5519** [comment]
Do you have Twitter Account?

**Comment by BogdanMakarchuk** [comment]
Yes, @Twertik_
