### ISSUE TITLE
Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 8192 bytes)

### ISSUE THREAD

**Issue by Driesboy** [Enes5519/EggWars#8]
Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 8192 bytes)
File: /src/pocketmine/utils/Config
Line: 130
Type: E_ERROR

**Comment by ExaSonit** [comment]
This crash is caused by a plugin, generally SurvivalGame/HungerGame

**Comment by Driesboy** [comment]
its this plugin!!

**Comment by Driesboy** [comment]
i have it only on this plugin so

**Comment by ExaSonit** [comment]
EggWars cause crash?

**Comment by Driesboy** [comment]
yep

**Comment by ExaSonit** [comment]
Only solution is remove plugin from your list

**Comment by ExaSonit** [comment]
I found this problem many times

**Comment by Driesboy** [comment]
i know but i think its he can fix it

**Comment by Driesboy** [comment]
fixed on my fork
